version: 2.1

jobs:
  checkmarx_scan:
    docker:
      - image: codehub-docker.jfrog.io/devops-checkmarx:latest
        auth:
          username: $ARTIFACTORY_USER
          password: $ARTIFACTORY_TOKEN
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start the Checkmarx scan
          command: |
            /opt/CxConsolePlugin/runCxConsole.sh Scan -v \
            -CxServer $CHECKMARX_SERVER \
            -Cxuser $CHECKMARX_USER \
            -CxPassword $CHECKMARX_PASSWORD \
            -ProjectName "CxServer\Accelerator\CRAFT" \
            -LocationType folder \
            -LocationPath ~/app \
            -Preset Default \
            -executepackagedependency \
            -ReportPDF ~/app/report/CRAFT_scan_results.pdf
      - store_artifacts:
          path: ~/app/report/CRAFT_scan_results.pdf
  blackduck_scan:
    docker:
      - image: circleci/openjdk:8u222-node
    working_directory: ~/app
    environment:
      COMMIT_ID: $(echo $CIRCLE_SHA1 | cut -c1-7)
    steps:
      - checkout
      - attach_workspace:
            at: workspace
      - run:
          name: Install npm packages
          command: npm install
      - run:
          name: Start the Synopsys Detect scan
          command: |
            bash ./.circleci/detect.sh \
            --blackduck.url=$BLACKDUCK_URL \
            --blackduck.api.token=$BLACKDUCK_TOKEN \
            --blackduck.timeout=600 \
            --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING \
            --detect.npm.path=/usr/bin/npm \
            --detect.npm.node.path=/usr/bin/node \
            --detect.project.name="CRAFT" \
            --detect.project.version.name="ver.$CIRCLE_BUILD_NUM.$COMMIT_ID" \
            --detect.risk.report.pdf=true \
            --detect.risk.report.pdf.path="~/app/report" \
            --detect.notices.report=true \
            --detect.notices.report.path="~/app/report"
      - store_artifacts:
          path: ~/app/report
workflows:
  scan:
    jobs:
      - checkmarx_scan:
          context: Codehub-Common
          filters:
            branches:
              only:
              - /sast\/.*/            # follow branching conventions matching the regex 
                                           # eg: sast/1, sast/prod 
                                           # to run sast scan #
      - blackduck_scan:
          context: Codehub-Common
          filters:
            branches:
              only:
              - /oss\/.*/             # follow branching conventions matching the regex 
                                            # eg: oss/1, oss/prod 
                                            # to run blackduck scan